### ISSUE TITLE
Support getattr

### ISSUE THREAD

**Issue by twheys** [dabeaz/sly#13]
In a Parser, given a function with multiple rules, where a statement is present in one rule but not the other, it would be useful to be able to use `getattr` on the `p` arg for that attribute, but currently a `KeyError` bubbles up.

```
    @_('NAME "(" ")"',
       'NAME "(" opt ")"')
    def rule(self, p):
        opt = getattr(p, 'opt', 'value')
        ...
```

When the first rule matches, without the value for opt, calling `getattr` results in a KeyError

```
  File ".../python3.6/site-packages/sly/yacc.py", line 1900, in parse
    value = p.func(self, pslice)
  File "...", line ..., in function
    args = getattr(p, 'arguments_list', [])
  File ".../python3.6/site-packages/sly/yacc.py", line 147, in __getattr__
    return self._slice[self._namemap[name]].value
```

**Comment by twheys** [comment]
As a workaround, I am using 

```
opt  = if 'opt' in p._namemap else []
```

However, it would be nice to not reference private values internal to sly.

**Comment by dabeaz** [comment]
Interesting.  I hadn't even thought of this use case, but I kind of like it.   I think you can check the length of the production using len(p) as a workaround as well, but allowing getattr() with an optional attribute seems like a good idea.

**Comment by twheys** [comment]
I could raise a PR with this addition if you'd like

**Comment by dabeaz** [comment]
I pushed a change (yesterday) that may have addressed this.  Give it a try.
