### ISSUE TITLE
YaccProduction index property causes AttributeError if index is 0.

### ISSUE THREAD

**Issue by ColMcp** [dabeaz/sly#14]
The index property of class YaccProduction is defined as
```
    @property
    def index(self):
        for tok in self._slice:
            if isinstance(tok, YaccSymbol):
                continue
            index = getattr(tok, 'index', None)
            if index:
                return index
        raise AttributeError('No index attribute found')

```
An index value of 0 is valid if the token is at the very start of the source text, but the `if index:` test for it is false so an AttributeError is raised.

Changing the test to `if index is not None:` fixes the problem).

**Comment by dabeaz** [comment]
Good catch!  Fixed.
