### ISSUE TITLE
How do I link Parsing Rules?

### ISSUE THREAD

**Issue by SaxonRah** [dabeaz/sly#21]
In ply, We would use a doc string like so
`'''program : program statement
               | statement'''`
then later something like
`'''statement : INTEGER command NEWLINE'''`
To link parsing rules to a token for use later.

How would you do something similar in sly?
All the examples I have seen are something like
`@_('program statement',
   'statement')`

So, how do I link the rules ('program statement', 'statement') to a token (program)?
Or rather define those rules as that token?

Is the function name the token that defines those rules in the decorator?
So I'd then use the function name in the decorators?

Like so ?
`@_('program statement', 'statement')`
`def program(p):
`
`@_('INTEGER command NEWLINE')`
`def statement(p):
  `
(I might not be using correct terminology)

**Comment by dabeaz** [comment]
The example at the end is how you do it:

    @_('program statement')
    def program(self, p):
          ...
   
    @_('statement')
    def program(self, p):
         ...

    @_('INTEGER command NEWLINE')
    def statement(self, p):
          ...

The function name is important.  If there's a reference to a non-terminal such as "statement", then there needs to be a matching function "statement".   The same function name may be defined more than once with different matching rules if necessary (as shown for program above).

**Comment by SaxonRah** [comment]
Ah, very nice, Thank you so much for the timely response and help, I really appreciate it. 

Also, thanks for ply and sly!
