### ISSUE TITLE
Silencing sly warnings?

### ISSUE THREAD

**Issue by MonliH** [dabeaz/sly#36]
Is there a way to disable the sly warnings? Here is an exmaple of one:

```
WARNING: Token 'EQEQ' defined, but not used
```
I have tried the ply way to diable (using `NullLogger`) but that doesn't work. Disabling the warnings isn't really documented and I can't find anything online.

Any help would be appreciated.

**Comment by dabeaz** [comment]
All warning messages are routed through a 'log' class attribute on the Parser class.  You can change it to something else using Python's logging module:

    import logging
    class MyParser(sly.Parser):
        log = logging.getLogger('whatever')
        
The output would then be controlled by logging configuration.   To silence it completely, you could use some kind of null-logger or other object for the log.

**Comment by MonliH** [comment]
I found a way to diable the logging. You have to set the level of the logger to `ERROR`:

```python
import logging
class MyParser(sly.Parser):
    log = logging.getLogger()
    log.setLevel(logging.ERROR)
```
