### ISSUE TITLE
Feature request: rename Lexer and Parser decorators

### ISSUE THREAD

**Issue by ColMcp** [dabeaz/sly#4]
Is there any particular reason for naming the decorators defined in the Lexer and Parser classes `'_'`? It's not very meaningful and I find them ugly in use since `@_(' ..... ')` essentially starts with four punctuation marks.
I messed around with the code and changed them to `@token` and `@rule` respectively. Suitably modified versions of the calculator examples seemed to work OK.

**Comment by dabeaz** [comment]
If the decorator was anything other than `@_` the project couldn't be called sly ;-).     This isn't something I'm likely to change because I like it.  You can always alias  `rule = _` in a class if you want to use something more verbose.

**Comment by ColMcp** [comment]
I had already tried aliasing in my Lexer and Parser subclasses but `_` seems to be undefined at that point. Is that the result of the `del attributes['_']` in the metaclass's `__new__()` method? (My understanding of Python metaclasses is sadly lacking.)

**Comment by dabeaz** [comment]
That _ variable is only visible in the class body. For example:

    class MyLexer(Lexer):
        token = _

        @token('...')
        def SPAM(self, t):
              ...

**Comment by ColMcp** [comment]
That was what I tried but, foolishly, I believed my IDE when it said `_` was undefined rather than actually try it in a Python interpreter. 
Sorry for the noise.

**Comment by lelit** [comment]
That's actually another relative downside of the approach taken to _inject_ the `_` decorator in the class namespace.

**Comment by pydanny** [comment]
Just tossing my hat into the ring, I like the use of the underscore. 😄

**Comment by chrisnorman7** [comment]
It had me confused for a while, as did the tokens set, not including any quotation marks.

Much as I appreciate the "slyness", I feel like this all may be too much magic (as I had to read the source code for the Lexer class before realising this wasn't a new Python feature I didn't know about).
