### ISSUE TITLE
Parsing binary SCPI data

### ISSUE THREAD

**Issue by dischoen** [dabeaz/sly#41]
Hi,
this is not an issue, more a question:
I would like to parse binary SCPI data of the form #{LoL}{L}{data}.
LoL is the length of the length field L.
L is the length of the binary data.
e.g. #210abcdefghij would be a valid binary data with LoL=2, L=10 and abc.. as data.
The problem here is that the length of the data has to be determined by parsing the header
and somehow feeding the length information to something like ".{L}"

Something like "#([1-9])([0-9]{\1})+(.{\2})" would be nice, where I could use the result of a group
inside of the current regex.
Embedded actions looked promising, but they happen in the parser.

**Comment by hadware** [comment]
My (late and naïve) guess is that you won't get any luck with Sly for that: the Lexer relies on regexes which can't handle this kind of contextual information.

Why would you want to use Sly for that kind of application?

**Comment by dischoen** [comment]
Pure naïveness, i guess. Lexx and yacc where the first tools which appeared on the radar, and I tried to solve my problem without thinking about the class of grammar.
In the meantime i have solved it with a simple state machine.
