### ISSUE TITLE
Aborting a parse

### ISSUE THREAD

**Issue by johnpote** [dabeaz/sly#42]
Thanks for SLY - very useful. Can you help? I have a small parser for reading a 'C' source code file and performing a translation on lines starting with "#rom". This is a non-standard statement available in Custom Computer Service's PIC compiler.
The modification I'm doing now requires the translation to be target processor specific so the first #rom statement must be the device type, some have 14 bit wide ROM words and others 16 bit. There is no point continuing if that statement is missing.
I have an SLY parser working but my solution to aborting the parse if an ordinary #rom statement appears before a #rom device statement seems awkward and heavy handed. Definitely not neat.
The 'deviceStmntErr error' production simply raises an exception.

	@_( 'deviceStmnt statements' )
	def root( self, p ):
		print("hv root")
		return True

	@_( 'deviceStmntErr error' )
	def root( self, p ):
		print("No device stmnt")
		raise CCSParserExcept("Device type statement missing")

	@_( 'deviceStmnt' )
	def deviceStmnt( self, p ):
		print("hv deviceStmnt:deviceStmnt")
		return

	@_( 'CCODE deviceStmnt' )
	def deviceStmnt( self, p ):
		print("hv deviceStmnt:CCODE deviceStmnt")
		return

	@_( '' )	#empty production
	def deviceStmntErr( self, p ):
		print("hv deviceStmntErr")
		return

	@_( 'HASHROM DEVICE STRING' )
	def deviceStmnt( self, p ):
		print("hv deviceStmnt")
		etc
	HASHROM, DEVICE & STRING are terminals from the lexer. The following is a valid device statement,
	'#rom device "PIC16F73"'.

What I'm wondering is is there a parser function in SLY that can tell the parser to receive an end of file for the next token rather than call the lexer for the next token? I could then return an abort code or message instead of raising the exception.
Any comments or feedback would be appreciated.

**Comment by dabeaz** [comment]
Honestly, I'd probably just do what you're doing.  Raise an exception.  Catch the exception in some outer code that initiates the parsing.   Potentially you could program some kind of interaction with the lexer to shut down and feed an EOF token, but it might be even messier compared to the exception approach.
