### ISSUE TITLE
Support for inclusive lexing states

### ISSUE THREAD

**Issue by SeanDS** [dabeaz/sly#50]
Is there support in SLY for the equivalent of PLY's [inclusive lexing states](http://www.dabeaz.com/ply/ply.html#ply_nn21)? It seems the default behaviour in SLY is equivalent to PLY's 'exclusive'. I find no mention of "exclusive" or "inclusive" in the source code.

EDIT: perhaps the idea is that, no, there is no inclusive lexing, but the lexer you define for the new state can inherit from the base one to get its tokens?

**Comment by PyPublishing** [comment]
Very, very late, but nonetheless:

You might find a solution in the [CHANGES](https://github.com/dabeaz/sly/blob/master/CHANGES) document.

Search "Version 0.3" changes, "4/1/2018   Support for **Lexer inheritance** added."

This should work on top of the (exclusive) "4/1/2018   Better support for lexing states."

**Comment by SeanDS** [comment]
Thanks for the reply. I'm glad this is now in SLY. I ended up just writing my own parser, as I think most people who need advanced features end up doing, but SLY was a great guide as to how to do it.
