### ISSUE TITLE
item from token

### ISSUE THREAD

**Issue by codykingham** [dabeaz/sly#55]
Please forgive if this is very dumb question, I am a beginner with yacc parsers.

I cannot understand why the minimalist example below throws a syntax error. The behavior I would 
expect from the grammar, `letters -> LETTER`, does not seem to work in this case.

```
test_string = 'At'

class TestLexer(Lexer):
    tokens = {LETTER}
    LETTER = '[a-zA-Z]'

class TestParser(Parser):    
    tokens = TestLexer.tokens

    @_('LETTER')
    def letters(self, p):
        return [p[0]]
    
t_lexer = TestLexer()
t_parser = TestParser()
t_parser.parse(t_lexer.tokenize(test_string))
```

**Comment by dabeaz** [comment]
The token you have defined only matches a single character as does the parser which expects a single LETTER.  The test string contains two LETTER tokens.  So, a syntax error.

**Comment by codykingham** [comment]
Thank you very much. I think I understand that.
