### ISSUE TITLE
Error: the calc_ebnf cannot be executed.

### ISSUE THREAD

**Issue by stark-zhang** [dabeaz/sly#58]
The example in calc_ebnf cannot run with python 3.8.3, following is the error reports:
> sly.yacc.YaccError: Unable to build grammar.
> C:\ProgramData\Miniconda3\lib\site-packages\sly\yacc.py:1690: Symbol 'PLUS|MINUS' used, but not defined as a token or a rule
> C:\ProgramData\Miniconda3\lib\site-packages\sly\yacc.py:1690: Symbol 'TIMES|DIVIDE' used, but not defined as a token or a rule

How to make ebnf work with sly?

**Comment by dabeaz** [comment]
The ability to specify a symbol such as `PLUS|MINUS` is literally the latest feature added to SLY and is not part of any pypi installable package because it's a work in progress.    If you want this, you'll need to pull the latest version directly from github.
