### ISSUE TITLE
ignore case sensitivity

### ISSUE THREAD

**Issue by ker2x** [dabeaz/sly#62]
I'm trying to have my language case insensitive.

I'm doing this : 
```python
class FortyLexer(Lexer):
    """Main Lexer Class for FortyFor"""
    Lexer.reflags = Lexer.regex_module.IGNORECASE

    tokens = {
        ID, NUMBER, PLUS, MINUS, TIMES, DIVIDE, ASSIGN, LPAR, RPAR,
        IF, ELSE
    }

    ignore = ' \t'
    ignore_comment = r'\!.*'
    ignore_newline = r'\n+'

    ID      = r'[a-zA-Z_][a-zA-Z0-9_]*'
    ID[r'if'] = IF
    ID[r'else'] = ELSE
...
```

"else" is recognized as an ELSE token, but "ELSE" is still recognized as an "ID".
Am i doing it wrong ?

i also tried with "    Lexer.reflags = Lexer.regex_module.RegexFlag.IGNORECASE"

**Comment by SunChuquin** [comment]
you can (?i:)

e.g: `FUN = r'(?i:fun_)'`

**Comment by classabbyamp** [comment]
```py
class MyLexer(sly.Lexer):
    reflags = re.IGNORECASE
    ...
```
this works just fine for me

**Comment by dabeaz** [comment]
case-insensitive keyword matching can be accomplished by writing a handler method

```
_keywords = { 'if', 'else', 'while', ... }

@_(r'[a-zA-Z_][a-zA-Z0-9_]*')
def ID(self, t):
     if t.value.lower() in _keywords:
         t.type = t.value().upper()
     return t
```

I don't know if SLY will be modified to support this through the array short-cut syntax.

**Comment by jschultz410** [comment]
@dabeaz I'm writing a SLY lexer for a language that has a **ton** of case-insensitive reserved keywords. 

For best speed, do you recommend using explicit matching rules for each keyword or is it better to have one broad regex and then refine the type like you did with the ID token in your previous post?

I'm assuming that I should unpack `_keywords` into `tokens` too somehow?
