### ISSUE TITLE
what does "@_" mean

### ISSUE THREAD

**Issue by wqh17101** [dabeaz/sly#77]
such as @_('expr')
i don`t know which decorator it used

**Comment by jpsnyder** [comment]
@wqh17101 In PyCharm you can add the following to the top of the `Lexer` and `Parser` classes to have it ignore those warnings.
```python
# noinspection PyUnresolvedReferences
class MyLexer(sly.Lexer):
```

**Comment by wqh17101** [comment]
> @wqh17101 In PyCharm you can add the following to the top of the `Lexer` and `Parser` classes to have it ignore those warnings.
> 
> ```python
> # noinspection PyUnresolvedReferences
> class MyLexer(sly.Lexer):
> ```

![image](https://user-images.githubusercontent.com/26429138/134479971-fff848e5-1b7e-48dc-be38-856a86fe3be7.png)
not work @jpsnyder
