### ISSUE TITLE
sly: Parse error in input. EOF

### ISSUE THREAD

**Issue by Pelfox** [dabeaz/sly#84]
Hi. I'm getting this error every time, when I'm using this code: 
```python
class SerialLexer(Lexer):
    tokens = { NAME, NUMBER, PLUS, MINUS, TIMES, DIVIDE, ASSIGN, LPAREN, RPAREN }
    ...
    ignore_comment = r'#.*'
...
```

```serial
# test
3 + 2
```

How can I fix it?

**Comment by dabeaz** [comment]
The error is being caused some issue in your grammar.  What does the parser look like?

**Comment by Pelfox** [comment]
https://gitlab.com/Pelfox/serial/-/blob/main/serial.py#L31

**Comment by dabeaz** [comment]
Is there a reduce/reduce conflict reported?

**Comment by Pelfox** [comment]
No

**Comment by dabeaz** [comment]
If the input file is literally what you show above, then it's being fed to the parser line-by-line.  The first line with the comment in it is "empty" (contains no statement or expression).   That's most likely the source of the error.

**Comment by Pelfox** [comment]
So, I tried with
```serial
# 
```
And it gives to me `sly: Parse error in input. EOF`

**Comment by dabeaz** [comment]
Right.  Because you're giving the parser empty input (no tokens). There are no parsing rules to match empty input.
