### ISSUE TITLE
Releases on pypi.org do not have tags

### ISSUE THREAD

**Issue by dvzrv** [dabeaz/sly#90]
Hi! I'm looking into packaging this project for Arch Linux.

Looking at the [releases on pypi.org](https://pypi.org/project/sly/#history) it appears that only the 0.1 release relates to a tag in this repository.

For downstreams it is essential to be able to relate to which commit in the source code relates to a release (for plain transparency and more practically also for being able to provide fixes and to relate to specific changes in the code base when reporting problems or fixing them).

Can you please add the missing tags? :)

**Comment by dabeaz** [comment]
noted
